name: Main CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  spec_biome:
    name: Run Biome in /spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./src
        working-directory: packages/spec
